# Form implementation generated from reading ui file 'ui/untitled.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from cinema_parser.resources import resources

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 720))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(10, 18, 27)")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lay1 = QtWidgets.QFrame(parent=self.centralwidget)
        self.lay1.setMaximumSize(QtCore.QSize(550, 50))
        self.lay1.setObjectName("lay1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.lay1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.lay1)
        self.label.setMinimumSize(QtCore.QSize(130, 50))
        self.label.setStyleSheet("color: rgb(229, 230, 206);\n"
"font-size: 14px;\n"
"font-family: \"cascadia code\"")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(parent=self.lay1)
        self.comboBox.setMinimumSize(QtCore.QSize(350, 50))
        self.comboBox.setStyleSheet("QComboBox {\n"
"    padding-left: 10px;\n"
"    font-size: 14px;\n"
"    background-color: rgba(20, 20, 20, 100);\n"
"    border: 1px solid rgba(0, 170, 255, 30);\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"    font-family: \"cascadia code\";\n"
"}\n"
"QComboBox::drop-down {\n"
"    background-color: rgb(226, 227, 210);\n"
"    width: 15px;\n"
"    border-radius: 5px;\n"
"}\n"
"QComboBox::drop-down:on{\n"
"    background-color: rgba(0, 189, 119, 200);\n"
"}\n"
"\n"
"QAbstractItemView {\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    background-color: rgba(200, 200, 200, 0);\n"
"    border: 1px solid rgba(90, 160, 155, 200);\n"
"    color: white;\n"
"}\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.pushButton = QtWidgets.QPushButton(parent=self.lay1)
        self.pushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"border: 1px solid rgba(0, 170, 255, 30);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: black;\n"
"}")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/refresh.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        
        self.pushButton2 = QtWidgets.QPushButton(parent=self.lay1)
        self.pushButton2.setMinimumSize(QtCore.QSize(120, 50))
        self.pushButton2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton2.setStyleSheet("QPushButton{\n"
"border: 1px solid rgba(0, 170, 255, 30);\n"
"border-radius: 5px;\n"
"font-family: \"cascadia code\";\n"
"font-size: 14px;\n"
"color: white;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: black;\n"
"}")
        self.pushButton2.setText("Повернутися")
        self.pushButton2.setObjectName("pushButton2")
        self.pushButton2.hide()
        self.horizontalLayout.addWidget(self.pushButton2)
        
        self.verticalLayout.addWidget(self.lay1)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(980, 640))
        self.tabWidget.setStyleSheet("    QTabWidget::pane { /* Убираем рамку вокруг содержимого */\n"
"        border-radius: 5px; /* Закругляем края */\n"
"        border: 1px solid rgba(0, 170, 255, 30);\n"
"        background: white; /* Цвет фона вкладок */\n"
"    }\n"
"\n"
"    QTabBar::tab { /* Скрываем вкладки */\n"
"        width: 0; /* Устанавливает ширину вкладки в 0 */\n"
"        height: 0; /* Устанавливает высоту вкладки в 0 */\n"
"        margin: 0;\n"
"        padding: 0;\n"
"        border: none;\n"
"    }")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.tab)
        self.scrollArea.setStyleSheet("QScrollArea{\n"
"    border: none;\n"
"}\n"
"QScrollArea QScrollBar:vertical {\n"
"    border: 0px;  /* Граница области скролла */\n"
"    background: rgba(0,0,0,0);        /* Фон скроллбара */\n"
"    width: 12px;                /* Ширина вертикального скроллбара */\n"
"    margin: 3px 0 3px 0;      /* Отступы сверху и снизу (чтобы кнопки не обрезались) */\n"
"}\n"
"QScrollArea QScrollBar::handle:vertical {\n"
"    border-radius: 3px;\n"
"    background: #111111;        /* Цвет ползунка */\n"
"    min-height: 5px;           /* Минимальная высота ползунка */\n"
"}\n"
"QScrollArea QScrollBar::handle:vertical:hover {\n"
"    border-radius: 3px;\n"
"    background: #FFDAB9;        /* Цвет ползунка */\n"
"    min-height: 5px;           /* Минимальная высота ползунка */\n"
"}\n"
"\n"
"QScrollArea QScrollBar::add-line:vertical {\n"
"    height: 0px;               /* Высота кнопки */\n"
"}\n"
"\n"
"QScrollArea QScrollBar::sub-line:vertical {\n"
"    height: 0px;               /* Высота кнопки */\n"
"}\n"
"\n"
"QScrollArea QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    border: none;               /* Убираем границу стрелок */\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollArea QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;           /* Цвет фона за ползунком */\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 978, 638))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea_2 = QtWidgets.QScrollArea(parent=self.tab_2)
        self.scrollArea_2.setStyleSheet("QScrollArea{\n"
"    border: none;\n"
"}\n"
"QScrollArea QScrollBar:vertical {\n"
"    border: 0px;  /* Граница области скролла */\n"
"    background: rgba(0,0,0,0);        /* Фон скроллбара */\n"
"    width: 12px;                /* Ширина вертикального скроллбара */\n"
"    margin: 3px 0 3px 0;      /* Отступы сверху и снизу (чтобы кнопки не обрезались) */\n"
"}\n"
"QScrollArea QScrollBar::handle:vertical {\n"
"    border-radius: 3px;\n"
"    background: #111111;        /* Цвет ползунка */\n"
"    min-height: 5px;           /* Минимальная высота ползунка */\n"
"}\n"
"QScrollArea QScrollBar::handle:vertical:hover {\n"
"    border-radius: 3px;\n"
"    background: #FFDAB9;        /* Цвет ползунка */\n"
"    min-height: 5px;           /* Минимальная высота ползунка */\n"
"}\n"
"\n"
"QScrollArea QScrollBar::add-line:vertical {\n"
"    height: 0px;               /* Высота кнопки */\n"
"}\n"
"\n"
"QScrollArea QScrollBar::sub-line:vertical {\n"
"    height: 0px;               /* Высота кнопки */\n"
"}\n"
"\n"
"QScrollArea QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    border: none;               /* Убираем границу стрелок */\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollArea QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;           /* Цвет фона за ползунком */\n"
"}")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 978, 638))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_6.setSpacing(15)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_3.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Кінотеатр:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Планета кіно LeoLand"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
